defaults:
  - base
  - _self_

candidate_preferred_spawn_biome:
  - "forest"

task_conf:
  - name: "mine"
    text: "mine_block:oak_log"

reward_conf:
  - event: "mine_block"
    max_reward_times: 1
    reward: 1.0
    objects:
      - "oak_log"
    identity: "mine oak_log"

init_inventory:
  - slot: 0
    type: "stone_axe"
    quantity: 1
